#!/bin/bash

curl https://goteleport.com/static/install.sh | bash -s ${teleport_version} ${teleport_edition}

# Edit the configuration below to enable any services you plan to run on your
# Teleport agent nodes. We recommend running the SSH Service at a minimum to
# enable secure access to the nodes.
echo ${token} > /var/lib/teleport/token
cat<<EOF >/etc/teleport.yaml
${agent_config}
EOF

systemctl restart teleport;

# Disable OpenSSH and any longstanding authorized keys.
systemctl disable --now ssh.service
find / -wholename "*/.ssh/authorized_keys" -delete

