version: v3
teleport:
  auth_token: /var/lib/teleport/token
  proxy_server: ${proxy_service_address}
app_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
auth_service:
  enabled: false
db_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
discovery_service:
  enabled: false
kubernetes_service:
  enabled: false
  resources:
  - labels:
      "*": "*"
proxy_service:
  enabled: false
ssh_service:
  enabled: true
  labels:
    role: agent-pool

